import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";

import "./globals.css";
import { THEME_INIT } from "@/lib/theme-init";

const jakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-sans",
  display: "swap",
});

// Force every route to render per-request. The CSP (proxy.ts) stamps a fresh
// per-request nonce into both the response header and Next's script tags; that
// only lines up when the HTML is generated per request. Statically prerendered
// pages bake their script tags at build time without the runtime nonce, so
// `strict-dynamic` blocks their chunks and the page never hydrates (the New
// Signal form, Settings, Calendar, Trash, Audit). Dynamic rendering keeps the
// nonce consistent. (This is why it worked in `next dev` but broke in prod.)
export const dynamic = "force-dynamic";

const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
const DESCRIPTION =
  "Turn company signals into founder-quality thought leadership. Context first, writing last.";

export const metadata: Metadata = {
  metadataBase: new URL(APP_URL),
  title: {
    default: "SignalStory — founder-quality content, context first",
    template: "%s — SignalStory",
  },
  description: DESCRIPTION,
  openGraph: {
    type: "website",
    siteName: "SignalStory",
    title: "SignalStory — founder-quality content, context first",
    description: DESCRIPTION,
    url: APP_URL,
    // The preview image is generated by app/opengraph-image.tsx (file convention),
    // which Next injects automatically — no static asset needed.
  },
  twitter: {
    card: "summary_large_image",
    title: "SignalStory — founder-quality content, context first",
    description: DESCRIPTION,
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={jakarta.variable} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT }} />
      </head>
      <body className="min-h-screen bg-background font-sans antialiased">
        {children}
      </body>
    </html>
  );
}
